### ISSUE TITLE
demo闪退

### ISSUE THREAD

**Issue by sangsais** [zhongjhATC/AlbumCameraRecorder#18]
Redmi note4 Android6.0
 
复现操作步骤
点击配置版-点击添加-长安录制（录制完点击取消按钮）-再次录制松手结束的时候就报错了

日志不够的话，我再放所有的，其实就是想用全屏视频录制的功能，这个库看你已经在线上使用了，录制视频的页面报错多不多（还望交流下，感谢），看了好些录制视频的库，看了看各自的issues，好多都是闪退，没敢确定用哪个。

04-25 18:26:29.238 31884-31884/com.zhongjh.cameraviewsoundrecorder E/InputEventReceiver: Exception dispatching input event.
04-25 18:26:29.238 31884-31884/com.zhongjh.cameraviewsoundrecorder E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
04-25 18:26:29.240 31884-31884/com.zhongjh.cameraviewsoundrecorder E/MessageQueue-JNI: java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet
        at android.animation.AnimatorSet.sortNodes(AnimatorSet.java:922)
        at android.animation.AnimatorSet.start(AnimatorSet.java:540)
        at com.zhongjh.albumcamerarecorder.widget.OperationLayout.startShowLeftRightButtonsAnimator(OperationLayout.java:293)
        at com.zhongjh.albumcamerarecorder.camera.CameraLayout$1.onLongClickEnd(CameraLayout.java:330)
        at com.zhongjh.albumcamerarecorder.widget.OperationLayout$1.onLongClickEnd(OperationLayout.java:194)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.reset(ClickOrLongButton.java:331)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.onTouchEvent(ClickOrLongButton.java:313)
        at android.view.View.dispatchTouchEvent(View.java:9430)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2447)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1766)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2863)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2408)
        at android.view.View.dispatchPointerEvent(View.java:9663)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4816)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4670)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4168)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4221)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4187)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4333)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4195)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4390)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4168)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4221)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4187)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4195)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4168)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6663)
    	at android.view.ViewRootImpl.doProcessInputEvents(ViewR
04-25 18:26:29.247 503-32551/? E/GraphicBufferSource: mLatestBufferUseCount is already 0.
04-25 18:26:29.305 31884-31884/com.zhongjh.cameraviewsoundrecorder E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zhongjh.cameraviewsoundrecorder, PID: 31884
    java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet
        at android.animation.AnimatorSet.sortNodes(AnimatorSet.java:922)
        at android.animation.AnimatorSet.start(AnimatorSet.java:540)
        at com.zhongjh.albumcamerarecorder.widget.OperationLayout.startShowLeftRightButtonsAnimator(OperationLayout.java:293)
        at com.zhongjh.albumcamerarecorder.camera.CameraLayout$1.onLongClickEnd(CameraLayout.java:330)
        at com.zhongjh.albumcamerarecorder.widget.OperationLayout$1.onLongClickEnd(OperationLayout.java:194)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.reset(ClickOrLongButton.java:331)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.onTouchEvent(ClickOrLongButton.java:313)
        at android.view.View.dispatchTouchEvent(View.java:9430)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2668)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2318)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2447)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1766)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2863)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2408)
        at android.view.View.dispatchPointerEvent(View.java:9663)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4816)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4670)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4168)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4221)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4187)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4333)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4195)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4390)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4168)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4221)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4187)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4195)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4168)
    	at android.view.ViewRootImpl.deliverInputEvent(Vie

**Comment by zhongjhATC** [comment]
已经修复该问题，可以看下
