### ISSUE TITLE
（续）小米6预览视频闪退，以及其它一些bug

### ISSUE THREAD

**Issue by FadedYu** [zhongjhATC/AlbumCameraRecorder#4]
### 运行环境
- [x]   设备型号：小米6
- [x]   设备系统版本：Android 8.0
- [x]   AlbumCameraRecorder版本：1.0.3
## 一 ：预览视频问题描述
在九宫格点击预览视频，点击播放视频时闪退（已找到原因）
### 报错原因
Android7.0 以后获取文件uri的方式改变。

在创建file对象后：`File file = new File(path);`  想要获取file的uri：
Android7.0之前，获取文件uri方式是：`Uri uri = Uri.fromFile(file);`
debug显示路径为：`file:///storage/emulated/0/DCIM/Camera/VIDEO_20190320_101452.mp4`，
Android7.0以后，不能直接获取`file://`路径，获取文件uri方式是：
```
Uri uri = FileProvider.getUriForFile(mContext, mContext.getPackageName() + ".fileprovider", file);
```
debug显示路径为：`content://com.zhongjh.cameraapp.fileprovider/app_path/DCIM/Camera/VIDEO_20190320_101452.mp4`

我看了**源码**发现只使用了`Uri uri = Uri.fromFile(file);`代码，并没有针对Android7.0使用`FileProvider`转换，Android7.0版本之前的机子运行时没问题，但是在Android7.0之后是不允许直接获取uri的，否则会报下面的错误日志。

### 闪退情况屏幕截图
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/28940136/54665153-264b8c00-4b21-11e9-86a7-bcc422e78a9e.gif)

### 闪退报错日志
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zhongjh.cameraviewsoundrecorder, PID: 14095
    android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/Camera/VIDEO_20190320_101452.mp4 exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2356)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9790)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9742)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
        at android.app.Activity.startActivityForResult(Activity.java:4536)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:233)
        at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:825)
        at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:939)
        at android.support.v4.app.Fragment.startActivity(Fragment.java:1002)
        at android.support.v4.app.Fragment.startActivity(Fragment.java:991)
        at com.zhongjh.albumcamerarecorder.preview.previewitem.PreviewItemFragment.lambda$onViewCreated$0(PreviewItemFragment.java:73)

        at com.zhongjh.albumcamerarecorder.preview.previewitem.-$$Lambda$PreviewItemFragment$iJg753nsOf9odWIyTXF0wuqREwo.onClick(Unknown Source:4)

        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

- #### 具体报错位置
[https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/multilibrary/src/main/java/com/zhongjh/albumcamerarecorder/preview/previewitem/PreviewItemFragment.java#L70](url)

### 解决方案
 判断Android7.0版本来执行不同的获取uri方法
```
    /**
     * 根据file文件获取该文件的uri，适配Android7.0以下版本
     * */
    public static Uri getUriForFile(Context mContext, File file) {
        Uri fileUri = null;
        // Android 版本判断
        if (Build.VERSION.SDK_INT >= 24) {
            fileUri = getUriForFile24(mContext, file);
        } else {
            fileUri = Uri.fromFile(file);
        }
        return fileUri;
    }

    /**
     * 根据file文件获取该文件的uri，Android7.0以上可直接调用
     * */
    public static Uri getUriForFile24(Context mContext, File file) {
        return FileProvider.getUriForFile(mContext, mContext.getPackageName() + ".fileprovider", file);
    }
```

### 问题描述
 先选择添加视频，然后再选择图片时，图片出现在添加按钮的后面。先图片后视频则没有这种情况。
### 问题截图
![Screenshot_200x356](https://user-images.githubusercontent.com/28940136/54665870-395f5b80-4b23-11e9-813a-6dc641c49ab9.png)
### 问题描述
录制的音频后缀为mp4格式，其实是不太好的，建议是单纯的mp3格式。有很多时候需要判断筛选出单独音频和视频或者其他文件，除了用mimeType之外，可能有时候因为特殊原因需要靠文件后缀来筛选。（是不是弄成全黑的视频，用视频声音来当做录音了2333 :satisfied:）
### 建议
可以跳转到调用手机自带的音频（不是很严谨），不用写界面了。

### 问题描述
好像并没有选择完文件后，获得全部文件数据的接口或方法，需要自己动手写。当全部选择好满意的图片视频音频后（中间省略各种删除添加操作），比如点击提交给后台时，可以直接调用接口获取这些全部文件信息，以便做相关的操作。

坑有点多，共勉~:satisfied:

**Comment by zhongjhATC** [comment]
前天一看到这些相关信息，非常感谢和激动！
这几天连夜赶时间修复了！并且独立出接口，相关你可以看看！关于你所提的第4点，本身有这个提供方法的！你可以看看！

 - [九宫格相关API](https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/progresslibrary/src/main/java/com/zhongjh/progresslibrary/api/MaskProgressApi.java).
 - [九宫格相关事件](https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/progresslibrary/src/main/java/com/zhongjh/progresslibrary/listener/MaskProgressLayoutListener.java).
 - [九宫格相关属性，配置UI等等](https://github.com/zhongjhATC/AlbumCameraRecorder/blob/master/progresslibrary/src/main/res/values/attrs.xml)

**Comment by FadedYu** [comment]
刚才我看了一下uri的问题，`FileProvider`**只能7.0以上能使用**，为了兼容Android 7.0以下的版本，所以7.0以下还是只能用`Uri uri = Uri.fromFile(file);`，可能我提供的解决方案的注释上有一些误解了233。

为了更好的兼容效果，可以在转换的方法里修改一下下：
```
    /**
     * 绑定路径
     */
    public Uri getUri(String path){
        //根据路径获取文件的uri，适配Android7.0以下版本
        if (Build.VERSION.SDK_INT >= 24) {
            return FileProvider.getUriForFile(mContext.get(), mSaveStrategy.authority, new File(path));
        } else {
            return Uri.fromFile(new File(path));
        }
    }
```
