### ISSUE TITLE
/AndroidRuntime: FATAL EXCEPTION: main     Process: cn.roc.openthecard, PID: 32269     java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/activity/result/contract/ActivityResultContracts$StartActivityForResult;         at com.zhongjh.albumcamerarecorder.camera.CameraFragment.onActivityResult(CameraFragment.java:134)         at com.zhongjh.albumcamerarecorder.camera.CameraFragment.onCreateView(CameraFragment.java:103) 

### ISSUE THREAD

**Issue by zhongjhATC** [zhongjhATC/AlbumCameraRecorder#52]
/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.roc.openthecard, PID: 32269
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/activity/result/contract/ActivityResultContracts$StartActivityForResult;
        at com.zhongjh.albumcamerarecorder.camera.CameraFragment.onActivityResult(CameraFragment.java:134)
        at com.zhongjh.albumcamerarecorder.camera.CameraFragment.onCreateView(CameraFragment.java:103)

**Comment by zhongjhATC** [comment]
据网友vane(953722572) 2022/7/26 23:31:31 说是如下解决的
    
implementation 'androidx.activity:activity-ktx:1.3.0'
    implementation 'androidx.fragment:fragment-ktx:1.3.2'

vane(953722572) 2022/7/26 23:32:24
multilibrary 这个库 没加这2个 可能编译出来加出现我发打那种错误

**Comment by zhongjhATC** [comment]
但是在项目里面其实增加 androidx.appcompat:appcompat 库即可

```
implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.4.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    // 图片
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'

    // 如果想简化代码并且同时用到multilibrary和progresslibrary、albumCameraRecorderCommon,可以直接使用combined库
    implementation 'com.github.zhongjhATC.AlbumCameraRecorder:combined:1.1.64X'

    // https://github.com/zetbaitsu/Compressor 另一款压缩库
    implementation 'id.zelory:compressor:2.1.1'

    // 公共库，如果不使用上面的combined库
    implementation 'com.github.zhongjhATC.AlbumCameraRecorder:common:1.1.64X'
    // 核心lib，调用显示相册、录屏、录音等
    implementation 'com.github.zhongjhATC.AlbumCameraRecorder:multilibrary:1.1.64X'
    // 配套使用，主要用于获取数据后进行相关显示，相应的上传进度显示，如果你只需要获取照片录像录音等数据，可以不需要使用这个
    implementation 'com.github.zhongjhATC.AlbumCameraRecorder:progresslibrary:1.1.64X'
    // It is mainly used to display the relevant upload progress after obtaining data. If you only need to obtain photos, videos and recordings, you don't need to use this
    implementation 'com.github.zhongjhATC.AlbumCameraRecorder:progresslibrary:1.1.64X'
```
