### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by langzhouzhou** [zhongjhATC/AlbumCameraRecorder#85]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/Glide;
                                                                                                    	at com.zhongjh.albumcamerarecorder.album.engine.impl.GlideEngine.loadUriImage(GlideEngine.kt:69)
                                                                                                    	at com.zhongjh.albumcamerarecorder.camera.ui.camera.adapter.PhotoAdapter.onBindViewHolder(PhotoAdapter.java:70)
                                                                                                    	at com.zhongjh.albumcamerarecorder.camera.ui.camera.adapter.PhotoAdapter.onBindViewHolder(PhotoAdapter.java:39)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
                                                                                                    	at android.view.View.measure(View.java:23560)
                                                                                                    	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                                    	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                                    	at android.view.View.measure(View.java:23560)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                                    	at android.view.View.measure(View.java:23560)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9681)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1657)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
                                                                                                    	at android.view.View.layout(View.java:21036)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6460)
                                                                                                    	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
                                                                                                    	at android.view.View.layout(View.java:21036)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6460)
                                                                                                    	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
                                                                                                    	at android.view.View.layout(View.java:21036)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6460)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                                    	at android.view.View.layout(View.java:21036)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6460)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
                                                                                                    	at android.view.View.layout(View.java:21036)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6460)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                                    	at android.view.View.layout(View.java:21036)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6460)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)

**Comment by ziXiong** [comment]
怎么解决的？  降低了glide的版本吗？
