### ISSUE TITLE
1.1.102X版本 在API 28调用拍照APP闪退

### ISSUE THREAD

**Issue by OliverGarfield** [zhongjhATC/AlbumCameraRecorder#93]
Caused by: java.lang.NoSuchMethodError: No virtual method close()V in class Landroid/content/res/TypedArray; or its super classes (declaration of 'android.content.res.TypedArray' appears in /system/framework/framework.jar)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.init(ClickOrLongButton.java:383)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.<init>(ClickOrLongButton.java:324)
        	... 94 more
    	Suppressed: java.lang.NoSuchMethodError: No virtual method close()V in class Landroid/content/res/TypedArray; or its super classes (declaration of 'android.content.res.TypedArray' appears in /system/framework/framework.jar)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.init(ClickOrLongButton.java:337)
        		... 95 more
    	Suppressed: java.lang.NoSuchMethodError: No virtual method close()V in class Landroid/content/res/TypedArray; or its super classes (declaration of 'android.content.res.TypedArray' appears in /system/framework/framework.jar)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.init(ClickOrLongButton.java:337)
        		... 95 more
    	Suppressed: java.lang.NoSuchMethodError: No virtual method close()V in class Landroid/content/res/TypedArray; or its super classes (declaration of 'android.content.res.TypedArray' appears in /system/framework/framework.jar)
        at com.zhongjh.albumcamerarecorder.widget.clickorlongbutton.ClickOrLongButton.init(ClickOrLongButton.java:337)
        		... 95 more

**Comment by OliverGarfield** [comment]
升级到1.1.103X后已经解决。
